const app=document.getElementById('app');
const state={page:'home',info:{},trials:[],self:[],scores:{},results:{},start:0};
const opts=['从不','偶尔','经常','总是'];
const selfItems=[['s1','emotion_stress','最近一周，我经常觉得压力很大。'],['s2','emotion_stress','最近一周，我容易烦躁或不开心。'],['s3','emotion_stress','最近一周，我觉得自己很难放松下来。'],['s4','anxiety_avoidance','遇到不确定的事情时，我会很担心。'],['s5','anxiety_avoidance','我常常害怕自己做错。'],['s6','anxiety_avoidance','如果一件事可能失败，我会想要避开它。'],['s7','low_motivation','最近一周，我对以前喜欢的事情兴趣减少。'],['s8','low_motivation','我觉得开始做事情比以前更困难。'],['s9','low_motivation','即使完成一件事，我也不太容易感到开心。'],['s10','social_adaptation','我常常担心同学不喜欢我。'],['s11','social_adaptation','我不太愿意主动和同学说话。'],['s12','social_adaptation','和别人发生误会时，我常常不知道怎么处理。']];
const games={chest:{title:'游戏一：不确定宝箱',rule:'每一轮请选择一个宝箱。系统会记录你面对确定、不确定和信息不足情境时的选择。',scenes:['你面前有三个宝箱，请选择一个打开。','这一次有一个宝箱提示不完整，你仍然需要做决定。','这一次时间较紧，请选择你更愿意打开的宝箱。'],choices:[['safe','安全宝箱：一定获得1个金币'],['uncertain','不确定宝箱：可能获得3个金币，也可能没有'],['incomplete','信息不足宝箱：提示不完整，但可能有惊喜'],['skip','跳过这一轮']]},storm:{title:'游戏二：风暴修复站',rule:'请在失败或困难情境中选择你最可能采取的做法。',scenes:['你修桥时发现材料不够，第一次尝试失败了。','你快修好灯塔时，系统提示方案错误。','时间快到了，小镇道路还没有修好。'],choices:[['adaptive','换一种方法再试一次'],['help','先看看提示或请求帮助'],['avoid','放弃这个任务'],['impulsive','随便选一个材料继续尝试']]},peer:{title:'游戏三：同伴小岛',rule:'请在同伴互动情境中选择你最可能采取的回应。',scenes:['你想加入同学的游戏，但他们正在讨论规则，没有马上回应你。','小组任务失败了，有同学说可能是你的部分出了问题。','你看到一个同学一个人坐着，好像不太开心。'],choices:[['prosocial','我可以一起参加吗？'],['withdrawal','算了，我不去了。'],['aggressive','你们不带我，我也不想理你们。'],['help','我们可以重新分工或找老师帮忙吗？']]}};
let gameOrder=['chest','storm','peer'],gameIndex=0,trialIndex=0,trialStart=0;
function html(s){app.innerHTML='<div class="wrap">'+s+'</div>'}
function age(b){const d=new Date(b),n=new Date();let y=n.getFullYear()-d.getFullYear(),m=n.getMonth()-d.getMonth();if(m<0||(m===0&&n.getDate()<d.getDate()))y--;return y}
function home(){html('<section class="card hero"><h1>学生情绪适应与心理风险游戏化筛查</h1><p>通过三个情境小游戏和简短问题，了解学生在情绪压力、焦虑回避、低动机、情绪调节和社交适应方面的风险线索。</p><div class="note">本工具仅用于研究分析和心理健康风险线索识别，不作为临床诊断依据。</div><button class="btn" onclick="consent()">开始测评</button></section>')}
function consent(){html('<section class="card"><h2>研究说明与知情同意</h2><div class="note"><p>本测评包含情境小游戏和简短自评题，预计用时10–15分钟。系统将记录基本信息、游戏选择、反应时间、自评题作答和风险线索结果。</p><p>结果仅用于研究分析和心理健康风险线索识别，不用于临床诊断。参与者可随时退出。</p></div><label class="check"><input id="agree" type="checkbox"> 我已阅读上述说明，并作为学生本人或其监护人，同意参与本次测评。</label><button class="btn" onclick="info()">我同意，继续</button></section>')}
function info(){if(document.getElementById('agree')&&!document.getElementById('agree').checked){alert('请先勾选知情同意。');return}html('<section class="card"><h2>基本信息</h2><div class="grid"><label>被试编号/昵称<input id="nickname"></label><label>性别<select id="gender"><option>男</option><option>女</option><option>其他</option><option>不愿透露</option></select></label><label>出生日期<input id="birth" type="date"></label><label>年级<select id="grade"><option>小学四年级</option><option>小学五年级</option><option>小学六年级</option><option>初一</option><option>初二</option><option>初三</option><option>高一</option><option>高二</option><option>高三</option></select></label><label>学校/机构编号<input id="school"></label><label>班级编号<input id="clazz"></label></div><button class="btn" onclick="saveInfo()">进入测评</button></section>')}
function saveInfo(){let n=document.getElementById('nickname').value.trim(),b=document.getElementById('birth').value;if(!n||!b){alert('请填写编号/昵称和出生日期。');return}state.info={nickname:n,gender:gender.value,birth_date:b,age:age(b),grade:grade.value,school_code:school.value,class_code:clazz.value,device:innerWidth<760?'手机':'电脑/平板',created_at:new Date().toISOString()};startGame()}
function startGame(){gameIndex=0;trialIndex=0;renderGame()}
function renderGame(){let key=gameOrder[gameIndex],g=games[key],total=g.scenes.length;let scene=g.scenes[trialIndex];let pct=Math.round(trialIndex/total*100);let choices=g.choices.map(c=>'<button class="choice" onclick="choose(\''+key+'\',\''+c[0]+'\')">'+c[1]+'</button>').join('');html('<section class="card"><h2>'+g.title+'</h2><div class="note">'+g.rule+'</div><div class="hud"><span>第 '+(trialIndex+1)+' / '+total+' 轮</span><div class="progress"><div class="bar" style="width:'+pct+'%"></div></div></div><div class="scene"><div class="scene-title">'+scene+'</div>'+choices+'</div></section>');trialStart=performance.now()}
function choose(game,choice){let rt=Math.round(performance.now()-trialStart);let extra={};if(game==='chest'){extra={safe:choice==='safe',uncertain:choice==='uncertain',incomplete:choice==='incomplete',skipped:choice==='skip'}}if(game==='storm'){extra={adaptive:choice==='adaptive',help:choice==='help',avoid:choice==='avoid',impulsive:choice==='impulsive'}}if(game==='peer'){extra={prosocial:choice==='prosocial',withdrawal:choice==='withdrawal',aggressive:choice==='aggressive',help:choice==='help'}}state.trials.push({game_name:game,trial_id:trialIndex+1,scenario_id:game+'_'+(trialIndex+1),selected_option_type:choice,response_time_ms:rt,extra_json:extra,timestamp:new Date().toISOString()});trialIndex++;if(trialIndex>=games[game].scenes.length){gameIndex++;trialIndex=0;if(gameIndex>=gameOrder.length)selfReport();else renderGame()}else renderGame()}
function selfReport(){let body=selfItems.map((it,i)=>'<div class="scene"><b>'+(i+1)+'. '+it[2]+'</b><div class="scale">'+opts.map((o,v)=>'<button id="q'+i+'_'+v+'" onclick="ans('+i+','+v+')">'+o+'</button>').join('')+'</div></div>').join('');html('<section class="card"><h2>简短心理风险自评题</h2><p class="note">请根据最近一周的情况作答。选项没有对错，请按真实感受选择。</p>'+body+'<button class="btn" onclick="finish()">提交测评</button></section>')}
function ans(i,v){state.self=state.self.filter(x=>x.item_id!==selfItems[i][0]);state.self.push({item_id:selfItems[i][0],dimension:selfItems[i][1],item_text:selfItems[i][2],response_value:v,response_label:opts[v],timestamp:new Date().toISOString()});for(let k=0;k<4;k++){let b=document.getElementById('q'+i+'_'+k);if(b)b.classList.remove('sel')}document.getElementById('q'+i+'_'+v).classList.add('sel')}
function level(n,mid,high){return n>=high?'高风险':n>=mid?'中风险':'低风险'}
function riskClass(r){return r==='高风险'?'high':r==='中风险'?'mid':'low'}
function calc(){let sum=d=>state.self.filter(x=>x.dimension===d).reduce((a,b)=>a+b.response_value,0);let chest=state.trials.filter(x=>x.game_name==='chest'),storm=state.trials.filter(x=>x.game_name==='storm'),peer=state.trials.filter(x=>x.game_name==='peer');let chestScore=chest.filter(x=>['safe','skip'].includes(x.selected_option_type)).length*2+chest.filter(x=>x.selected_option_type==='incomplete').length;let stormScore=storm.filter(x=>['avoid','impulsive'].includes(x.selected_option_type)).length*3+storm.filter(x=>x.selected_option_type==='help').length;let peerScore=peer.filter(x=>['withdrawal','aggressive'].includes(x.selected_option_type)).length*3;let scores={emotion_stress:{self:sum('emotion_stress'),game:0},anxiety_avoidance:{self:sum('anxiety_avoidance'),game:chestScore},low_motivation:{self:sum('low_motivation'),game:0},emotion_regulation:{self:sum('emotion_stress')+Number((state.self.find(x=>x.item_id==='s12')||{}).response_value||0),game:stormScore},social_adaptation:{self:sum('social_adaptation'),game:peerScore}};Object.keys(scores).forEach(k=>{let s=scores[k];let selfRisk=level(s.self,4,7),gameRisk=level(s.game,4,7);s.self_risk=selfRisk;s.game_risk=gameRisk;s.risk=(selfRisk==='高风险'||gameRisk==='高风险'||(selfRisk==='中风险'&&gameRisk==='中风险'))?'高风险':(selfRisk==='中风险'||gameRisk==='中风险')?'中风险':'低风险'});let risks=Object.values(scores).map(x=>x.risk);let overall=risks.includes('高风险')||risks.filter(x=>x==='中风险').length>=3?'高风险':risks.includes('中风险')?'中风险':'低风险';state.scores=scores;state.results={overall_risk:overall,dimension_risks:scores}}
async function finish(){if(state.self.length<selfItems.length){alert('请完成所有自评题。');return}calc();html('<section class="card"><h2>测评已完成</h2><div class="success">感谢参与。本结果仅用于研究分析和心理健康风险线索识别，不作为临床诊断依据。</div><div id="save" class="note">正在保存测评数据到后台……</div><button class="btn ghost" onclick="location.reload()">重新测评</button></section>');try{let res=await fetch('/api/assessments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'mental_health_gba',info:state.info,results:state.results,scores:state.scores,trials:state.trials,self_report_items:state.self})});let d=await res.json();document.getElementById('save').className='success';document.getElementById('save').textContent='数据已保存到后台。记录编号：'+d.id}catch(e){document.getElementById('save').className='warn';document.getElementById('save').textContent='数据未保存成功。请确认已通过后台服务打开页面。'}}
home();
